--- 
kind: pipeline
name: default

platform: 
  arch: arm
  os: linux

steps:
- name: build
  image: golang
  commands:
  - go get
  - go build
 

- name: publish 
  image: plugins/docker
  registry: hub.docker.com
  repo: zabov
  tags: 
    - armv7
    - ARM
    - latest